login_info:
  accessType: 'USERNAME'
  code: null
  customerId: '{{DNI}}'
  deviceId: '{{MYINVESTOR_DEVICE}}'
  otpId: null
  password: '{{MYINVESTOR_PWD}}'
  plataform: null 
endpoints:
  login: 'https://app.myinvestor.es/ms-keycloak/api/v1/auth/token'
  accounts: 'https://app.myinvestor.es/myinvestor-server/rest/protected/cuentas/efectivo'
  portfolios: 'https://app.myinvestor.es/myinvestor-server/rest/protected/inversiones'
  movements: 'https://app.myinvestor.es/myinvestor-server/rest/protected/cuentas/consulta-movimientos-efectivo'
  stocks: 'https://app.myinvestor.es/ms-broker/v1/acciones/resumen-acciones-cliente'
  real_state: 'https://app.myinvestor.es/urbanitae/v1/users/U109574/allInvestments'
data_mapping:
  cash:
    id: 'ibanCuenta'
    name: 'aliasCuenta'
    initial_value: 'importeCuenta'
    value: 'importeCuenta'
  stock:
    id: ''
    name: ''
    initial_value: ''
    value: ''
  etf:
    id: 'isin'
    name: 'nombre'
    initial_value: 'importeInversionPlusvalias'
    value: 'ValorMercadoPlusvalia'
    etfs: 'accionesEtfDtoList'
  fund:
    id: 'isin'
    name: 'nombreInversion'
    initial_value: 'importeInicial'
    value: 'importe'
  portfolio:
    id: 'idCuenta'
    name: 'aliasCuenta'
    initial_value: 'totalInvertido'
    value: 'valorMercado'
    acc: 'inversionesCuentaValores'
    funds: 'inversionesDtoList'
  crypto:
    id: ''
    name: ''
    initial_value: ''
    value: ''
  bond:
    id: ''
    name: ''
    initial_value: ''
    value: ''
  realestate:
    id: 'projectId'
    name: 'projectName'
    initial_value: 'investedQuantity'
    value: 'investedQuantity'